Linear Algebra in code


In [ ]:
import torch
import numpy as np

a = torch.IntTensor(3,2)
b = torch.IntTensor(3,2)

a


tensor([[133941376,         0],
        [       27,         0],
        [       -1,         0]], dtype=torch.int32)

In [ ]:
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Here we just created a 3x2 matrix

# Matrix multipy

In [ ]:
import torch
import numpy as np
a = torch.FloatTensor([[1,2,3],[3,2,1],[3,3,3]])
b = torch.FloatTensor([[13,13,13],[3,2,1],[1,2,3]])
torch.mm(a, b, out=None)


tensor([[22., 23., 24.],
        [46., 45., 44.],
        [51., 51., 51.]])

# Gauss-Jordan Elimination using python 

## page of helpful torch info

https://pytorch.org/docs/master/torch.html#torch.gesv

consider the video 
https://www.youtube.com/watch?v=0fTSBIBD7Cs



*   x+y+2z = -1
*   x+3y-6z = 7
*   2x-y+2z = 0

What is the goal?
convert this junk above into something that looks like this 
[1,0,0, a] which means 1*x+0*y+0*z=a
so mainly x = a

similarly a=x, b=y, c=z


step 1 augment the matrix 


In [1]:
import torch

# Define the augmented matrix
aug = torch.FloatTensor([[10,3,5, 13], [2,9,10, 1], [12,19,10, 19]])
print("Augmented matrix:")
print(aug)

# Get the size of the matrix
size = aug.size()
width = size[1]
length = size[0]

for k in range(length):
    # Find the row with the maximum value in column k
    max_index = torch.argmax(torch.abs(aug[k,k])) + k
    
    # Swap the current row with the row containing the maximum value
    if k != max_index:
        aug[[k, max_index]] = aug[[max_index, k]]
    
    # Check if the pivot is 0
    if aug[k, k] == 0:
        print("Pivot is 0, cannot proceed with Gaussian elimination.")
        break
    
    # Divide the current row by the pivot
    aug[k] = aug[k] / aug[k, k]
    
    # Subtract the current row from all the other rows to get zeros in the lower triangle
    for i in range(length):
        if i == k:
            continue
        factor = aug[i, k]
        aug[i] -= factor * aug[k]

print("Result:")
print(aug)


Augmented matrix:
tensor([[10.,  3.,  5., 13.],
        [ 2.,  9., 10.,  1.],
        [12., 19., 10., 19.]])
Result:
tensor([[ 1.0000,  0.0000,  0.0000,  1.4476],
        [ 0.0000,  1.0000,  0.0000,  0.3524],
        [-0.0000, -0.0000,  1.0000, -0.5067]])
